CREATE TABLE IF NOT EXISTS users(
	id serial PRIMARY KEY, -- autogenerated id
	email text, -- email
	first_name text NOT NULL, -- first name
	last_name text NOT NULL, -- last name
	birthday timestamptz NOT NULL, -- birthday!
	phone_number text, -- optional phone number
	photo_bucket text, -- s3 bucket
	photo_key text, -- key to s3
	subid text, -- cognito id
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	archived_at timestamptz
);
