name: apply migrations
on: [workflow_dispatch]
jobs:
  apply-migrations:
    runs-on: ubuntu-latest
    container: migrate/migrate:v4.10.0
    steps:
      - uses: actions/checkout@v2
      - name: apply migrations
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        run: migrate -database $POSTGRES_URL -path migrations up