name: build and deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - name: run tests
        run: go test -count=1 -p=1 ./...

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: change to infrastructure directory
        run: cd infra
      - name: install aws cdk globally
        run: sudo npm i -g aws-cdk
      - name: install packages
        run: npm install
        env:
          CI: true
      - name: synthesize cloudformation template
        run: cdk synth
      - name: bootstrap
        run: cdk bootstrap
      - name: deploy updated infrastructure!
        run: cdk deploy --require-approval never

  apply-migrations:
    needs: deploy
    runs-on: ubuntu-latest
    container: migrate/migrate:v4.10.0
    steps:
      - name: apply migrations
        run: migrate -database $POSTGRES_URL -path migrations up